import type { Curriculum } from "./types";

/**
 * The Go curriculum map, fundamental → advanced. It is intentionally
 * comprehensive (it names every major area of the language and toolchain, drawn
 * from go.dev/learn and the go.dev/doc index) while `status` stays honest about
 * how much interactive lesson content is authored. Only Module 0's core lesson
 * is "authored" today; the rest are inspectable and carry official references.
 */
export const goCurriculum: Curriculum = {
  course: "go",
  title: "Go Runtime Lab",
  tagline: "Build correct mental models of Go — from source file to running system.",
  modules: [
    {
      id: "go-0",
      order: 0,
      level: "fundamental",
      title: "How Go Becomes a Process",
      description:
        "Trace source through compilation, linking, initialization, runtime startup, and a running executable.",
      prerequisiteModuleIds: [],
      project: {
        title: "Go execution & value inspector",
        outcome: "A CLI that reports its build target, runtime version, and init trace.",
        milestones: ["Deterministic startup trace", "Build metadata injection", "Cross-compile matrix"],
      },
      resources: [
        {
          label: "Installing Go",
          url: "https://go.dev/doc/install",
          kind: "doc",
          description: "Official install instructions for every platform.",
        },
        {
          label: "Tutorial: Get started with Go",
          url: "https://go.dev/doc/tutorial/getting-started",
          kind: "doc",
          description: "Write, run, and understand your first Go program.",
        },
        {
          label: "Spec: Package initialization and program execution",
          url: "https://go.dev/ref/spec#Program_initialization_and_execution",
          kind: "doc",
          description: "The normative rules for init order and program start.",
        },
        {
          label: "golang/go",
          url: "https://github.com/golang/go",
          kind: "repo",
          description: "The compiler, linker, runtime, and standard library source.",
          stars: "126k",
        },
      ],
      topics: [
        {
          id: "go-source-to-process",
          title: "From source file to running process",
          summary: "What the toolchain and runtime do before main runs.",
          concepts: ["compilation", "linking", "initialization", "runtime", "build-cache", "cross-compilation"],
          prerequisites: [],
          whyNow: "Everything you deploy is a binary; understanding it first makes every later bug legible.",
          learnerOutcome: "Explain compile → link → load → init → main and predict initialization order.",
          ledgerFlowApplication: "Ship a reproducible LedgerFlow API binary with deterministic startup.",
          status: "authored",
          lessonId: "go-source-to-process",
        },
        {
          id: "go-toolchain-modules",
          title: "The go tool, modules & workspaces",
          summary: "go build/run/test, modules, versioning, the build cache, and workspaces.",
          concepts: ["go-command", "modules", "go.mod", "semantic-import-versioning", "workspaces", "build-cache"],
          prerequisites: ["go-source-to-process"],
          whyNow: "Real projects are modules; the tool decides what compiles and what is cached.",
          learnerOutcome: "Manage dependencies, versions, and multi-module workspaces confidently.",
          ledgerFlowApplication: "Structure LedgerFlow as a module with reproducible builds.",
          status: "authored",
          lessonId: "go-toolchain-modules",
          resources: [
            {
              label: "How to Write Go Code",
              url: "https://go.dev/doc/code",
              kind: "doc",
              description: "The canonical guide to organizing code, packages, and modules.",
            },
            {
              label: "Go Modules Reference",
              url: "https://go.dev/ref/mod",
              kind: "doc",
              description: "The complete reference for modules, versions, and go.mod.",
            },
            {
              label: "Tutorial: Create a Go module",
              url: "https://go.dev/doc/tutorial/create-module",
              kind: "doc",
              description: "Build and consume your own module step by step.",
            },
            {
              label: "Tutorial: Multi-module workspaces",
              url: "https://go.dev/doc/tutorial/workspaces",
              kind: "doc",
              description: "Work across multiple modules at once with go.work.",
            },
          ],
        },
      ],
    },
    {
      id: "go-1",
      order: 1,
      level: "fundamental",
      title: "Values & Program Execution",
      description: "The value model: types, zero values, constants, copy semantics, functions, and control flow.",
      prerequisiteModuleIds: ["go-0"],
      project: {
        title: "Data transformation CLI",
        outcome: "A small CLI that parses, transforms, and prints structured values.",
        milestones: ["Typed parsing", "Pure transformation functions", "Deterministic output"],
      },
      resources: [
        {
          label: "A Tour of Go — Basics",
          url: "https://go.dev/tour/basics/1",
          kind: "playground",
          description: "Interactive introduction to values, functions, and control flow.",
        },
        {
          label: "Effective Go",
          url: "https://go.dev/doc/effective_go",
          kind: "doc",
          description: "Idiomatic use of the constructs in this module.",
        },
        {
          label: "quii/learn-go-with-tests",
          url: "https://github.com/quii/learn-go-with-tests",
          kind: "repo",
          description: "Learn these fundamentals test-first.",
          stars: "23k",
        },
      ],
      topics: [
        {
          id: "go-basic-types",
          title: "Basic types, constants & zero values",
          summary: "Numeric, string, and boolean types; untyped constants; the zero value.",
          concepts: ["types", "untyped-constants", "zero-values", "conversions"],
          prerequisites: ["go-source-to-process"],
          whyNow: "Every program is values; Go's defaults and constant rules prevent whole bug classes.",
          learnerOutcome: "Predict zero values and how untyped constants convert.",
          ledgerFlowApplication: "Model money and identifiers with the right base types.",
          status: "authored",
          lessonId: "go-basic-types",
        },
        {
          id: "go-copy-semantics",
          title: "Variables, assignment & copy semantics",
          summary: "Assignment copies values; scope and shadowing; when a copy bites.",
          concepts: ["assignment", "copy-semantics", "scope", "shadowing"],
          prerequisites: ["go-basic-types"],
          whyNow: "Go copies by value by default — the source of many surprises.",
          learnerOutcome: "Reason about when data is copied versus shared.",
          ledgerFlowApplication: "Avoid accidental aliasing of transaction records.",
          status: "authored",
          lessonId: "go-copy-semantics",
        },
        {
          id: "go-functions-defer",
          title: "Functions, multiple returns, defer & closures",
          summary: "First-class functions, multiple return values, defer ordering, and closures.",
          concepts: ["functions", "multiple-returns", "defer", "closures"],
          prerequisites: ["go-copy-semantics"],
          whyNow: "defer and closures shape how Go handles cleanup and callbacks.",
          learnerOutcome: "Use defer for reliable cleanup and understand closure capture.",
          ledgerFlowApplication: "Guarantee resource release in request handlers.",
          status: "authored",
          lessonId: "go-functions-defer",
        },
        {
          id: "go-control-flow",
          title: "Control flow: if, for, switch",
          summary: "The single loop keyword, expression/type switches, and labels.",
          concepts: ["if", "for", "switch", "labels"],
          prerequisites: ["go-basic-types"],
          whyNow: "Go's minimal control flow is quick to master and shapes idiom.",
          learnerOutcome: "Write idiomatic loops and switches.",
          ledgerFlowApplication: "Branch cleanly on transaction states.",
          status: "authored",
          lessonId: "go-control-flow",
        },
      ],
    },
    {
      id: "go-2",
      order: 2,
      level: "fundamental",
      title: "Memory & Data Structures",
      description: "Slices, maps, strings, structs, and pointers — plus stack/heap and escape analysis.",
      prerequisiteModuleIds: ["go-1"],
      project: {
        title: "File-based expense manager",
        outcome: "Store and query records using slices, maps, and structs.",
        milestones: ["Struct modeling", "Slice/map operations", "Aliasing-safe updates"],
      },
      resources: [
        {
          label: "Go blog: Slices — usage and internals",
          url: "https://go.dev/blog/slices-intro",
          kind: "article",
          description: "How slice headers and backing arrays actually work.",
        },
        {
          label: "Go blog: Strings, bytes, runes and characters",
          url: "https://go.dev/blog/strings",
          kind: "article",
          description: "UTF-8, runes, and the truth about string indexing.",
        },
        {
          label: "inancgumus/learngo",
          url: "https://github.com/inancgumus/learngo",
          kind: "repo",
          description: "Hundreds of exercises on slices, maps, and structs.",
          stars: "20k",
        },
      ],
      topics: [
        {
          id: "go-slices",
          title: "Arrays, slices & backing arrays",
          summary: "Slice headers, capacity, append/reallocation, and aliasing traps.",
          concepts: ["arrays", "slices", "backing-array", "append", "aliasing"],
          prerequisites: ["go-copy-semantics"],
          whyNow: "Slices are everywhere and their aliasing behavior causes real bugs.",
          learnerOutcome: "Predict when append reallocates and when slices share memory.",
          ledgerFlowApplication: "Batch transactions without aliasing corruption.",
          status: "planned",
        },
        {
          id: "go-maps",
          title: "Maps",
          summary: "Map semantics, the comma-ok idiom, and unordered iteration.",
          concepts: ["maps", "comma-ok", "iteration-order"],
          prerequisites: ["go-slices"],
          whyNow: "Maps are the default associative structure; iteration order surprises many.",
          learnerOutcome: "Use maps correctly and avoid ordering assumptions.",
          ledgerFlowApplication: "Index accounts by id for O(1) lookup.",
          status: "planned",
        },
        {
          id: "go-strings-runes",
          title: "Strings, bytes & runes",
          summary: "Immutable strings, []byte, runes, and UTF-8 encoding.",
          concepts: ["strings", "bytes", "runes", "unicode", "utf-8"],
          prerequisites: ["go-basic-types"],
          whyNow: "Text handling is a common source of correctness bugs.",
          learnerOutcome: "Iterate text safely by rune, not byte.",
          ledgerFlowApplication: "Normalize and validate user-entered descriptions.",
          status: "planned",
        },
        {
          id: "go-structs-pointers",
          title: "Structs, pointers & methods",
          summary: "Composite types, pointers, and value vs pointer receivers.",
          concepts: ["structs", "pointers", "receivers"],
          prerequisites: ["go-copy-semantics"],
          whyNow: "Structs and pointers are how Go models domain data and behavior.",
          learnerOutcome: "Choose value vs pointer receivers deliberately.",
          ledgerFlowApplication: "Model accounts and transactions as structs.",
          status: "planned",
        },
        {
          id: "go-stack-heap-escape",
          title: "Stack, heap & escape analysis",
          summary: "Where values live, escape analysis, and a GC overview.",
          concepts: ["stack", "heap", "escape-analysis", "garbage-collection"],
          prerequisites: ["go-structs-pointers"],
          whyNow: "Knowing where values live explains performance and lifetime.",
          learnerOutcome: "Reason about allocation without premature tuning.",
          ledgerFlowApplication: "Keep hot request paths allocation-light.",
          status: "planned",
          resources: [
            {
              label: "A Guide to the Go Garbage Collector",
              url: "https://go.dev/doc/gc-guide",
              kind: "doc",
              description: "How the GC manages heap memory and its costs.",
            },
          ],
        },
      ],
    },
    {
      id: "go-3",
      order: 3,
      level: "intermediate",
      title: "Type System & Abstraction",
      description: "Interfaces, method sets, type assertions, embedding, and generics.",
      prerequisiteModuleIds: ["go-2"],
      project: {
        title: "Modular transaction engine",
        outcome: "Compose behavior behind interfaces with generic helpers.",
        milestones: ["Consumer-defined interfaces", "Type-safe generics", "Composable engine"],
      },
      resources: [
        {
          label: "Tutorial: Generics",
          url: "https://go.dev/doc/tutorial/generics",
          kind: "doc",
          description: "Official introduction to type parameters and constraints.",
        },
        {
          label: "Go blog: When to use generics",
          url: "https://go.dev/blog/when-generics",
          kind: "article",
          description: "Guidance on when generics help and when they don't.",
        },
        {
          label: "tmrts/go-patterns",
          url: "https://github.com/tmrts/go-patterns",
          kind: "repo",
          description: "Idiomatic abstraction and composition patterns.",
          stars: "24k",
        },
      ],
      topics: [
        {
          id: "go-interfaces",
          title: "Interfaces, method sets & nil interfaces",
          summary: "Implicit satisfaction, method sets, and the typed-nil trap.",
          concepts: ["interfaces", "method-sets", "nil-interface", "typed-nil"],
          prerequisites: ["go-structs-pointers"],
          whyNow: "Interfaces are Go's core abstraction — and typed nil is a classic bug.",
          learnerOutcome: "Define small interfaces and avoid the typed-nil pitfall.",
          ledgerFlowApplication: "Abstract storage behind a repository interface.",
          status: "planned",
        },
        {
          id: "go-assertions-switches",
          title: "Type assertions & type switches",
          summary: "Safely recover concrete types from interface values.",
          concepts: ["type-assertion", "type-switch"],
          prerequisites: ["go-interfaces"],
          whyNow: "Needed to handle heterogeneous values without breaking type safety.",
          learnerOutcome: "Use the comma-ok assertion and type switches correctly.",
          ledgerFlowApplication: "Dispatch on event types in a ledger.",
          status: "planned",
        },
        {
          id: "go-embedding",
          title: "Embedding & composition",
          summary: "Struct/interface embedding as Go's answer to inheritance.",
          concepts: ["embedding", "composition", "promotion"],
          prerequisites: ["go-interfaces"],
          whyNow: "Composition over inheritance is idiomatic Go.",
          learnerOutcome: "Compose behavior with embedding instead of subclassing.",
          ledgerFlowApplication: "Layer middleware and decorators.",
          status: "planned",
        },
        {
          id: "go-generics",
          title: "Generics: type parameters & constraints",
          summary: "Type parameters, constraints, and type inference.",
          concepts: ["generics", "type-parameters", "constraints", "inference"],
          prerequisites: ["go-interfaces"],
          whyNow: "Generics remove a class of duplication and unsafe casts.",
          learnerOutcome: "Write reusable, type-safe generic functions and types.",
          ledgerFlowApplication: "Build a generic, type-safe result/collection helper.",
          status: "planned",
        },
      ],
    },
    {
      id: "go-4",
      order: 4,
      level: "intermediate",
      title: "Errors & Program Design",
      description: "Error values, wrapping and inspection, panic/recover, and dependency direction.",
      prerequisiteModuleIds: ["go-3"],
      project: {
        title: "Robust transaction validator",
        outcome: "Layered error handling with wrapping and clear boundaries.",
        milestones: ["Sentinel/typed errors", "errors.Is/As", "Boundary-owned recovery"],
      },
      resources: [
        {
          label: "Go blog: Error handling and Go",
          url: "https://go.dev/blog/error-handling-and-go",
          kind: "article",
          description: "The foundational article on errors as values.",
        },
        {
          label: "Go blog: Working with Errors in Go 1.13",
          url: "https://go.dev/blog/go1.13-errors",
          kind: "article",
          description: "Wrapping with %w and inspecting with Is/As/Unwrap.",
        },
        {
          label: "uber-go/guide",
          url: "https://github.com/uber-go/guide",
          kind: "repo",
          description: "Battle-tested conventions for errors and design.",
          stars: "17k",
        },
      ],
      topics: [
        {
          id: "go-error-values",
          title: "Errors are values",
          summary: "The error interface, sentinel errors, and typed errors.",
          concepts: ["error-interface", "sentinel-errors", "typed-errors"],
          prerequisites: ["go-interfaces"],
          whyNow: "Go's explicit errors are central to reliable programs.",
          learnerOutcome: "Design error values that callers can act on.",
          ledgerFlowApplication: "Return actionable validation errors from the domain.",
          status: "planned",
        },
        {
          id: "go-error-wrapping",
          title: "Wrapping & inspecting errors",
          summary: "%w, errors.Is, errors.As, and Unwrap.",
          concepts: ["wrapping", "errors.Is", "errors.As", "unwrap"],
          prerequisites: ["go-error-values"],
          whyNow: "Wrapping preserves context without losing the ability to inspect.",
          learnerOutcome: "Add context while keeping errors inspectable.",
          ledgerFlowApplication: "Trace a failure from handler down to storage.",
          status: "planned",
        },
        {
          id: "go-panic-recover",
          title: "panic, recover & when to use them",
          summary: "Panics for truly exceptional states; recover at boundaries only.",
          concepts: ["panic", "recover", "deferred-recovery"],
          prerequisites: ["go-functions-defer"],
          whyNow: "Misusing panic turns bugs into outages.",
          learnerOutcome: "Reserve panic for programmer errors; recover only at edges.",
          ledgerFlowApplication: "Convert a handler panic into a 500 without crashing the server.",
          status: "planned",
        },
        {
          id: "go-dependency-direction",
          title: "Dependency direction & interfaces at the consumer",
          summary: "Accept interfaces, return structs; define interfaces where used.",
          concepts: ["dependency-inversion", "consumer-interfaces", "package-design"],
          prerequisites: ["go-interfaces"],
          whyNow: "Good boundaries keep large programs changeable.",
          learnerOutcome: "Point dependencies inward and keep packages decoupled.",
          ledgerFlowApplication: "Keep the domain independent of the database.",
          status: "planned",
        },
      ],
    },
    {
      id: "go-5",
      order: 5,
      level: "intermediate",
      title: "Standard Library & I/O",
      description: "Reader/Writer, files, JSON, time, context, HTTP, and CLIs.",
      prerequisiteModuleIds: ["go-4"],
      project: {
        title: "HTTP financial data service",
        outcome: "A small JSON HTTP service built on the standard library.",
        milestones: ["Reader/Writer composition", "JSON encoding", "HTTP handlers + middleware"],
      },
      resources: [
        {
          label: "Tutorial: Developing a RESTful API with Gin",
          url: "https://go.dev/doc/tutorial/web-service-gin",
          kind: "doc",
          description: "Official tutorial building a JSON web service.",
        },
        {
          label: "Standard library reference (pkg.go.dev/std)",
          url: "https://pkg.go.dev/std",
          kind: "doc",
          description: "Every standard package, searchable with examples.",
        },
        {
          label: "go-chi/chi",
          url: "https://github.com/go-chi/chi",
          kind: "repo",
          description: "A lightweight, idiomatic HTTP router built on net/http.",
          stars: "19k",
        },
        {
          label: "spf13/cobra",
          url: "https://github.com/spf13/cobra",
          kind: "repo",
          description: "The de-facto library for building Go CLIs.",
          stars: "39k",
        },
      ],
      topics: [
        {
          id: "go-io-reader-writer",
          title: "io.Reader & io.Writer",
          summary: "The two interfaces that compose all of Go's I/O.",
          concepts: ["io.Reader", "io.Writer", "streaming", "composition"],
          prerequisites: ["go-interfaces"],
          whyNow: "Almost all I/O in Go flows through these two interfaces.",
          learnerOutcome: "Compose readers and writers to stream data.",
          ledgerFlowApplication: "Stream large exports without buffering everything.",
          status: "planned",
        },
        {
          id: "go-files-os",
          title: "Files, os & environment",
          summary: "Working with the filesystem, processes, and environment.",
          concepts: ["os", "files", "environment"],
          prerequisites: ["go-io-reader-writer"],
          whyNow: "Programs must read config and files safely.",
          learnerOutcome: "Handle files and env with correct error paths.",
          ledgerFlowApplication: "Load configuration and import files.",
          status: "planned",
        },
        {
          id: "go-json",
          title: "JSON encoding & decoding",
          summary: "encoding/json, struct tags, and streaming codecs.",
          concepts: ["encoding/json", "struct-tags", "marshal", "unmarshal"],
          prerequisites: ["go-structs-pointers"],
          whyNow: "JSON is the lingua franca of services.",
          learnerOutcome: "Model and (de)serialize JSON safely.",
          ledgerFlowApplication: "Encode API responses and decode requests.",
          status: "planned",
        },
        {
          id: "go-time-context",
          title: "time & context",
          summary: "Durations, deadlines, and context propagation basics.",
          concepts: ["time", "context", "deadlines", "cancellation"],
          prerequisites: ["go-functions-defer"],
          whyNow: "Deadlines and cancellation are foundational to servers.",
          learnerOutcome: "Propagate deadlines and cancel work correctly.",
          ledgerFlowApplication: "Bound every request with a context deadline.",
          status: "planned",
        },
        {
          id: "go-net-http",
          title: "net/http: servers, handlers & middleware",
          summary: "Handlers, the mux, middleware, and the client.",
          concepts: ["net/http", "handlers", "middleware", "http-client"],
          prerequisites: ["go-io-reader-writer", "go-json"],
          whyNow: "HTTP is how most Go services communicate.",
          learnerOutcome: "Build a small HTTP service with middleware.",
          ledgerFlowApplication: "Serve the LedgerFlow API on net/http.",
          status: "planned",
          resources: [
            {
              label: "Writing Web Applications",
              url: "https://go.dev/doc/articles/wiki/",
              kind: "doc",
              description: "The classic end-to-end net/http tutorial (the wiki app).",
            },
          ],
        },
        {
          id: "go-database-sql",
          title: "Accessing relational databases (database/sql)",
          summary: "Handles, queries, prepared statements, transactions, and avoiding SQL injection.",
          concepts: ["database/sql", "connection-pool", "prepared-statements", "transactions", "sql-injection"],
          prerequisites: ["go-error-wrapping", "go-time-context"],
          whyNow: "Almost every backend service talks to a database; Go's database/sql is the foundation.",
          learnerOutcome: "Query, mutate, and transact safely with database/sql.",
          ledgerFlowApplication: "Persist LedgerFlow transactions with safe, pooled SQL.",
          status: "planned",
          resources: [
            {
              label: "Tutorial: Accessing a relational database",
              url: "https://go.dev/doc/tutorial/database-access",
              kind: "doc",
              description: "Official step-by-step database/sql tutorial.",
            },
            {
              label: "Accessing relational databases (guide)",
              url: "https://go.dev/doc/database/index",
              kind: "doc",
              description: "In-depth guide: handles, pools, transactions, cancellation.",
            },
            {
              label: "Avoiding SQL injection risk",
              url: "https://go.dev/doc/database/sql-injection",
              kind: "doc",
              description: "Use parameterized queries — never string-concatenate SQL.",
            },
          ],
        },
      ],
    },
    {
      id: "go-6",
      order: 6,
      level: "advanced",
      title: "Concurrency",
      description: "Goroutines, the scheduler, channels, sync primitives, context, races, and patterns.",
      prerequisiteModuleIds: ["go-5"],
      project: {
        title: "Concurrent transaction processor",
        outcome: "A safe, cancellable pipeline with bounded concurrency.",
        milestones: ["Worker pool", "Cancellation with context", "Race-free shared state"],
      },
      resources: [
        {
          label: "Go blog: Go concurrency patterns — pipelines",
          url: "https://go.dev/blog/pipelines",
          kind: "article",
          description: "Building and cancelling pipelines of goroutines.",
        },
        {
          label: "Go blog: Context",
          url: "https://go.dev/blog/context",
          kind: "article",
          description: "Propagating cancellation and deadlines across goroutines.",
        },
        {
          label: "golang.org/x/sync (errgroup, semaphore)",
          url: "https://pkg.go.dev/golang.org/x/sync",
          kind: "repo",
          description: "Official supplementary concurrency primitives.",
        },
        {
          label: "sourcegraph/conc",
          url: "https://github.com/sourcegraph/conc",
          kind: "repo",
          description: "Structured concurrency helpers that prevent leaks.",
          stars: "9k",
        },
        {
          label: "Rob Pike — Go Concurrency Patterns (video)",
          url: "https://www.youtube.com/watch?v=f6kdp27TYZs",
          kind: "video",
          description: "The classic talk that builds the mental model for this module.",
        },
      ],
      topics: [
        {
          id: "go-goroutines-scheduler",
          title: "Goroutines & the scheduler",
          summary: "Cheap concurrency and the GMP scheduling model.",
          concepts: ["goroutines", "scheduler", "GMP", "blocking"],
          prerequisites: ["go-functions-defer"],
          whyNow: "Goroutines are trivial to start and easy to misuse.",
          learnerOutcome: "Reason about how goroutines are scheduled and block.",
          ledgerFlowApplication: "Process transactions concurrently without oversubscription.",
          status: "planned",
        },
        {
          id: "go-channels-select",
          title: "Channels & select",
          summary: "Communicating by sharing channels; select and directions.",
          concepts: ["channels", "select", "buffering", "close"],
          prerequisites: ["go-goroutines-scheduler"],
          whyNow: "Channels are Go's primary coordination primitive.",
          learnerOutcome: "Coordinate goroutines with channels and select safely.",
          ledgerFlowApplication: "Fan work out and collect results.",
          status: "planned",
        },
        {
          id: "go-sync-atomic",
          title: "Mutexes & atomics",
          summary: "When shared memory beats channels; sync and sync/atomic.",
          concepts: ["sync.Mutex", "sync.WaitGroup", "atomic"],
          prerequisites: ["go-goroutines-scheduler"],
          whyNow: "Some state is simplest guarded, not passed.",
          learnerOutcome: "Choose between channels and locks deliberately.",
          ledgerFlowApplication: "Protect an in-memory balance cache.",
          status: "planned",
        },
        {
          id: "go-context-cancellation",
          title: "Context & cancellation",
          summary: "Propagating cancellation and deadlines through goroutines.",
          concepts: ["context", "cancellation", "deadlines", "leaks"],
          prerequisites: ["go-channels-select", "go-time-context"],
          whyNow: "Uncancelled goroutines leak and hang shutdowns.",
          learnerOutcome: "Wire cancellation through a goroutine tree.",
          ledgerFlowApplication: "Cancel in-flight work on shutdown.",
          status: "planned",
        },
        {
          id: "go-races-detector",
          title: "Data races & the race detector",
          summary: "What a data race is and how -race finds them.",
          concepts: ["data-race", "race-detector", "happens-before"],
          prerequisites: ["go-sync-atomic"],
          whyNow: "Races are silent, nondeterministic, and dangerous.",
          learnerOutcome: "Detect and eliminate data races.",
          ledgerFlowApplication: "Prove concurrent balance updates are race-free.",
          status: "planned",
          resources: [
            {
              label: "The Go Memory Model",
              url: "https://go.dev/ref/mem",
              kind: "doc",
              description: "The happens-before rules that define correct concurrency.",
            },
          ],
        },
        {
          id: "go-concurrency-patterns",
          title: "Patterns: pipelines, fan-in/out, worker pools",
          summary: "Composable patterns and when sequential is better.",
          concepts: ["pipelines", "fan-in", "fan-out", "worker-pool", "structured-concurrency"],
          prerequisites: ["go-channels-select", "go-context-cancellation"],
          whyNow: "Patterns turn primitives into reliable systems.",
          learnerOutcome: "Assemble cancellable, leak-free concurrent pipelines.",
          ledgerFlowApplication: "Build a bounded transaction-processing pipeline.",
          status: "planned",
        },
      ],
    },
    {
      id: "go-7",
      order: 7,
      level: "advanced",
      title: "Testing & Tooling",
      description: "Table tests, benchmarks, fuzzing, mocks, coverage, vet, and profiling.",
      prerequisiteModuleIds: ["go-6"],
      project: {
        title: "Tested & profiled ledger core",
        outcome: "A well-tested package with benchmarks and a profiling pass.",
        milestones: ["Table + fuzz tests", "Benchmarks", "pprof-guided optimization"],
      },
      resources: [
        {
          label: "Tutorial: Add a test",
          url: "https://go.dev/doc/tutorial/add-a-test",
          kind: "doc",
          description: "Official intro to Go's testing package.",
        },
        {
          label: "Tutorial: Fuzzing",
          url: "https://go.dev/doc/tutorial/fuzz",
          kind: "doc",
          description: "Find edge-case bugs automatically with fuzzing.",
        },
        {
          label: "Diagnostics (profiling, tracing, debugging)",
          url: "https://go.dev/doc/diagnostics",
          kind: "doc",
          description: "The official guide to pprof, traces, and the race detector.",
        },
        {
          label: "stretchr/testify",
          url: "https://github.com/stretchr/testify",
          kind: "repo",
          description: "Popular assertion and mocking toolkit.",
          stars: "24k",
        },
        {
          label: "golangci/golangci-lint",
          url: "https://github.com/golangci/golangci-lint",
          kind: "repo",
          description: "The standard aggregated Go linter.",
          stars: "16k",
        },
      ],
      topics: [
        {
          id: "go-unit-table-tests",
          title: "Unit & table-driven tests",
          summary: "The testing package and idiomatic table tests.",
          concepts: ["testing", "table-tests", "subtests", "t.Run"],
          prerequisites: ["go-functions-defer"],
          whyNow: "Tests are part of writing Go, not an afterthought.",
          learnerOutcome: "Write clear, table-driven tests with subtests.",
          ledgerFlowApplication: "Cover balance rules with table tests.",
          status: "planned",
        },
        {
          id: "go-benchmarks",
          title: "Benchmarks",
          summary: "Measuring with testing.B and reading the numbers.",
          concepts: ["benchmarks", "b.N", "allocs"],
          prerequisites: ["go-unit-table-tests"],
          whyNow: "Measure before you optimize.",
          learnerOutcome: "Write benchmarks and interpret ns/op and allocs/op.",
          ledgerFlowApplication: "Benchmark the hot posting path.",
          status: "planned",
        },
        {
          id: "go-fuzzing",
          title: "Fuzzing",
          summary: "Native fuzzing to surface edge-case failures.",
          concepts: ["fuzzing", "corpus", "seed"],
          prerequisites: ["go-unit-table-tests"],
          whyNow: "Fuzzing finds bugs your examples miss.",
          learnerOutcome: "Write a fuzz test and triage findings.",
          ledgerFlowApplication: "Fuzz the transaction parser.",
          status: "planned",
        },
        {
          id: "go-mocks-fakes",
          title: "Mocks, fakes & test doubles",
          summary: "Interfaces make substitution easy; prefer fakes.",
          concepts: ["mocks", "fakes", "interfaces", "dependency-injection"],
          prerequisites: ["go-interfaces"],
          whyNow: "Good doubles keep tests fast and focused.",
          learnerOutcome: "Substitute dependencies without heavy mocking.",
          ledgerFlowApplication: "Fake the store to test the service.",
          status: "planned",
        },
        {
          id: "go-vet-coverage",
          title: "Coverage, go vet & static analysis",
          summary: "Coverage, go vet, and golangci-lint in a workflow.",
          concepts: ["coverage", "go-vet", "static-analysis", "linting"],
          prerequisites: ["go-unit-table-tests"],
          whyNow: "Tooling catches whole classes of mistakes for free.",
          learnerOutcome: "Wire vet, lint, and coverage into your loop.",
          ledgerFlowApplication: "Gate merges on vet + lint + coverage.",
          status: "planned",
        },
        {
          id: "go-profiling-pprof",
          title: "Profiling with pprof & the race detector",
          summary: "CPU/memory profiles and the -race flag.",
          concepts: ["pprof", "cpu-profile", "heap-profile", "race-detector"],
          prerequisites: ["go-benchmarks"],
          whyNow: "Profiles direct optimization to what matters.",
          learnerOutcome: "Capture and read a pprof profile.",
          ledgerFlowApplication: "Find and fix an allocation hotspot.",
          status: "planned",
        },
      ],
    },
    {
      id: "go-8",
      order: 8,
      level: "advanced",
      title: "Runtime, Performance & the Deep End",
      description: "Escape analysis in depth, GC tuning, reflection, unsafe/cgo, and advanced modules.",
      prerequisiteModuleIds: ["go-7"],
      project: {
        title: "LedgerFlow Core, optimized",
        outcome: "A performance-hardened core with measured, justified changes.",
        milestones: ["Escape-analysis pass", "GC/alloc tuning", "Reflection-based codec (justified)"],
      },
      resources: [
        {
          label: "A Guide to the Go Garbage Collector",
          url: "https://go.dev/doc/gc-guide",
          kind: "doc",
          description: "How the GC works and how to reason about its costs.",
        },
        {
          label: "The Go Memory Model",
          url: "https://go.dev/ref/mem",
          kind: "doc",
          description: "The formal happens-before guarantees.",
        },
        {
          label: "google/pprof",
          url: "https://github.com/google/pprof",
          kind: "repo",
          description: "The profiling visualization tool itself.",
          stars: "8k",
        },
        {
          label: "Go Modules Reference",
          url: "https://go.dev/ref/mod",
          kind: "doc",
          description: "Deep reference for versioning, replace, and vendoring.",
        },
      ],
      topics: [
        {
          id: "go-escape-analysis-deep",
          title: "Escape analysis in depth",
          summary: "Reading -gcflags=-m and shaping allocation.",
          concepts: ["escape-analysis", "gcflags", "inlining", "allocation"],
          prerequisites: ["go-stack-heap-escape", "go-profiling-pprof"],
          whyNow: "Allocation is often the biggest performance lever.",
          learnerOutcome: "Explain why a value escapes and reduce allocations.",
          ledgerFlowApplication: "Cut allocations on the posting path.",
          status: "planned",
        },
        {
          id: "go-gc-tuning",
          title: "GC behavior & tuning",
          summary: "GOGC, the memory limit, and pacing.",
          concepts: ["GOGC", "GOMEMLIMIT", "gc-pacing"],
          prerequisites: ["go-stack-heap-escape"],
          whyNow: "GC settings trade memory for CPU under load.",
          learnerOutcome: "Tune GC with evidence, not guesswork.",
          ledgerFlowApplication: "Set a memory limit for the service container.",
          status: "planned",
        },
        {
          id: "go-reflection",
          title: "Reflection",
          summary: "reflect: power, cost, and when to avoid it.",
          concepts: ["reflect", "type-info", "struct-tags"],
          prerequisites: ["go-interfaces", "go-json"],
          whyNow: "Reflection powers codecs but erodes type safety.",
          learnerOutcome: "Use reflection sparingly and safely.",
          ledgerFlowApplication: "Understand how JSON tags drive encoding.",
          status: "planned",
        },
        {
          id: "go-unsafe-cgo",
          title: "unsafe & cgo",
          summary: "Escaping the type system and calling C — and the costs.",
          concepts: ["unsafe.Pointer", "cgo", "static-vs-dynamic-linking"],
          prerequisites: ["go-stack-heap-escape"],
          whyNow: "Sometimes required for interop or performance, always risky.",
          learnerOutcome: "Know when unsafe/cgo is justified and their trade-offs.",
          ledgerFlowApplication: "Decide static vs dynamic linking for deployment.",
          status: "planned",
        },
        {
          id: "go-modules-advanced",
          title: "Modules, versioning & release",
          summary: "Semantic import versioning, replace, vendoring, and releases.",
          concepts: ["semver", "replace", "vendoring", "retract"],
          prerequisites: ["go-toolchain-modules"],
          whyNow: "Shipping libraries and services needs disciplined versioning.",
          learnerOutcome: "Version and release Go modules correctly.",
          ledgerFlowApplication: "Cut a reproducible LedgerFlow release.",
          status: "planned",
        },
      ],
    },
  ],
};
